
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>FontLoader</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="SevenZip">
      <HintPath>lib\SevenZip.dll</HintPath>
    </Reference>
    <Reference Include="SharpFont.NetStandard">
      <HintPath>lib\SharpFont.NetStandard.dll</HintPath>
    </Reference>
    <Reference Include="Velentr.Collections">
      <HintPath>lib\Velentr.Collections.dll</HintPath>
    </Reference>
    <Reference Include="Velentr.Font.FNA">
      <HintPath>lib\Velentr.Font.FNA.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>